name: Bug report
description: If you are experiencing issues with bleh’s functionality, here’s the place to get help
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: "sorry you are having trouble >~<"
  - type: input
    id: contact
    attributes:
      label: Username
      description: Please enter your Last.fm username
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Please mention what you were trying to do and also what you expected to happen (post screenshots if you can)
    validations:
      required: true
  - type: input
    id: bleh
    attributes:
      label: bleh
      description: What version of bleh are you using?
      placeholder: eg. 2025.????
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: eg. Chrome, Firefox, Safari
    validations:
      required: true
  - type: checkboxes
    id: pro
    attributes:
      label: Last.fm Pro
      description: Are you subscribed to Last.fm?
      options:
        - label: "Yes"
        - label: "No"
  - type: input
    id: language
    attributes:
      label: Language
      description: Which language do you have selected in bleh?
      value: English
  - type: input
    id: extension
    attributes:
      label: Extension
      description: Which extension are you using to run bleh?
      value: Tampermonkey
